### ISSUE TITLE
Adaptar a QGIS2.6

### ISSUE THREAD

**Issue by midraed** [INTA-Suelos/QGIS-R-Geostatistics#1]
Dialogos no se muestran. Posiblemente haya cambiado un poco la estructura del codigo. Revisar los cambios.

**Comment by angelini75** [comment]
Que es esto @midraed ?

**Comment by midraed** [comment]
Me parece que cambio la estructura de los plugins de R en QGIS y no anda
mas... lo mismo necesita confirmacion. Si podes probalo.

**Comment by midraed** [comment]
Pufff esto se arreglo hace mucho...
