### ISSUE TITLE
Reflotar proyecto

### ISSUE THREAD

**Issue by midraed** [INTA-Suelos/QGIS-R-Geostatistics#2]
Recien tuve una reunión con Roberto Ahumada, que esta haciendo su tesis. Uno de sus objetivos es muy similar a este. Por lo que va a contribuir al proyecto. Claro que por ahora vamos a mantener los cambios de manera privada. Voy a hacer una rama de este proyecto y la voy a forkear a un repositorio privado de los mios*. Te doy acceso Marcos así podes ver los aportes, pero van a ser privados por ahora. Hemos acordado que luego sus aportes se van a integrar al proyecto original y con codigo abierto.

*Si, me pague una cuenta de github... y tengo unos repos privados. Me sobran un par por las dudas.

**Comment by dariorodriguez** [comment]
En criollo porfi

El 23 de julio de 2015, 18:20, Guillermo Federico Olmedo <
notifications@github.com> escribió:

> Recien tuve una reunión con Roberto Ahumada, que esta haciendo su tesis.
> Uno de sus objetivos es muy similar a este. Por lo que va a contribuir al
> proyecto. Claro que por ahora vamos a mantener los cambios de manera
> privada. Voy a hacer una rama de este proyecto y la voy a forkear a un
> repositorio privado de los mios*. Te doy acceso Marcos así podes ver los
> aportes, pero van a ser privados por ahora. Hemos acordado que luego sus
> aportes se van a integrar al proyecto original y con codigo abierto.
> 
> *Si, me pague una cuenta de github... y tengo unos repos privados. Me
> sobran un par por las dudas.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/INTA-Suelos/QGIS-R-Geostatistics/issues/2.

## 

Darío

**Comment by angelini75** [comment]
Totalmente de acuerdo.
